### ISSUE TITLE
connection issues.

### ISSUE THREAD

**Issue by SPulivarthi** [francozappa/knob#8]
Hi,
i'm trying the knob attack on rooted nexus5.
got the following errors:

----------------------------------------------------------------------------------------
[*] Importing fw_5 for Nexus 5
[!] Could not read btsnoop header
[+] Starting local process '/usr/bin/adb': pid 14442
[+] Receiving all data: Done (0B)
[*] Process '/usr/bin/adb' stopped with exit code 0 (pid 14442)
[+] Starting local process '/usr/bin/adb': pid 14445
[+] Receiving all data: Done (0B)
[*] Process '/usr/bin/adb' stopped with exit code 0 (pid 14445)
[CRITICAL] No connection to target device.
[*] Check if:
     -> Bluetooth is active
     -> Bluetooth Stack has Debug Enabled
     -> BT HCI snoop log is activated
[CRITICAL] No connection to target device.
---------------------------------------------------------------------------------------

The bluetooth, HCI snoop log are active. Also, stack is debug enabled following the procedure here for nexus 5 https://github.com/seemoo-lab/internalblue/blob/master/android_bluetooth_stack/README.md.

am i missing something here?

**Comment by francozappa** [comment]
Hi @SPulivarthi,

I'm assuming that Bluetooth is enabled in the nexus 5 when you run `internalblue`.

I guess that you have to install the Bluetooth stack provided in my [repo](
https://github.com/francozappa/knob/tree/master/poc-internalblue/internalblue/android_bluetooth_stack) instead of the one provided by the seemoo-lab guys.
